### ISSUE TITLE
не инжектиться ._.

### ISSUE THREAD

**Issue by Pyroks** [PlutoSolutions/DeadCode#3]

**Comment by mr-nv** [comment]
скрин

**Comment by mr-nv** [comment]
и какой у тебя комп

**Comment by Pyroks** [comment]
то есть, всё идёт как по маслу, но после того как всё кончается, он просто не инжектится. У мя 11 винда, ASUS TUF gaming F15

**Comment by mr-nv** [comment]
у тебя тлаунчер легаси?

**Comment by Pyroks** [comment]
+

**Comment by mr-nv** [comment]
че

**Comment by mr-nv** [comment]
ладно напиши дискорд свой я тебя добавлю, может быть помогу

**Comment by Pyroks** [comment]
Я использовал фикс TL legacy, всё заворкало

**Comment by mr-nv** [comment]
че за фикс

**Comment by Pyroks** [comment]
А мне его киданул модер дк

**Comment by Pyroks** [comment]
Можем в войс пойти
