### ISSUE TITLE
РАТКИ нет?

### ISSUE THREAD

**Issue by oyzipfile** [PlutoSolutions/DeadCode#9]

**Comment by mr-nv** [comment]
есть

**Comment by mr-nv** [comment]
обсуждение ратки в кряке дедкода стартует здесь
как вам производительность? мы старались оптимизировать ратник чтоб он проц и видюху не жрал

**Comment by NCPUser** [comment]
> есть

Есть И Точка.

**Comment by purpl3-yt** [comment]
> обсуждение ратки в кряке дедкода стартует здесь как вам производительность? мы старались оптимизировать ратник чтоб он проц и видюху не жрал

Вроде норм, спасибо
